#!/bin/sh

LOG="$(git log -1)"
echo $LOG

eval $(ssh-agent -s)
chmod 600 .travis/id_rsa
ssh-add .travis/id_rsa
git clone git@github.com:opentraveldata/optd.git /tmp/optd

cat .travis/synchronization_file_map.csv | while read line ; do
  old=$(echo $line | cut -d^ -f1)
  new=$(echo $line | cut -d^ -f2)
  cp "$new" /tmp/optd/"$old"
done

cd /tmp/optd
git status
#git commit -a -m "$LOG"
#git push
