#!/bin/sh
#
# Synchronization hook between this repo (opentraveldata/opentraveldata)
# and the old one (opentraveldata/optd)
#
# To use this, just add a line in .travis/synchronization_file_map.csv,
# in the following order: $old^$new
# The separator is ^, meaning that we do not support the character '^' in
# file names. If this breaks your code, please update this setup in order
# to use a different character for separator.
#

# Starts an ssh-agent
eval $(ssh-agent -s)
# The key is decrypted by travis (it is stored encrypted in our repo)
chmod 600 .travis/id_rsa
# Import the key
ssh-add .travis/id_rsa
# Clone the old repo
git clone git@github.com:opentraveldata/optd.git /tmp/optd

# Synchronize the files
cat .travis/synchronization_file_map.csv | while read line ; do
  old=$(echo $line | cut -d^ -f1)
  new=$(echo $line | cut -d^ -f2)
  if [ ! -f "$new" ] ; then
    echo "The file '$new' (in this repo) is missing."
    echo "It is needed to keep '$old' (in opentraveldata/optd) updated"
    echo "If you moved this file, please update .travis/synchronization_file_map.csv"
    exit 1
  fi
  echo "copying '$new' in 'optd/$old'"
  cp "$new" /tmp/optd/"$old"
done

# Get the log of the last commit
LOG="$(git log -1)"
cd /tmp/optd
git status
#git commit -a -m "$LOG"
#git push
