#!/bin/sh

# Master hook
#
# Runs all files in the hooks directory, in alphanumerical order, only if
# they are executable. This file is not executable on purpose, such that
# it does not self-runs.

status=0

for hook in .travis/hooks/* ; do
  [ -x $hook ] || continue

  echo "\nRunning hook ./$hook\n"
  ./$hook
  st=$?
  if [ $st != 0 ] ; then
    echo "\nThe hook ./$hook failed! (exited with status $st)\n"
    # if a hook fails, exit immediately
    exit $st
  else
    echo "\nThe hook ./$hook was a success!\n"
  fi
done
