#!/bin/sh

LOG="$(git log -1)"
echo $LOG

chmod 600 .travis/id_rsa
ssh-add .travis/id_rsa
git clone git@github.com:opentraveldata/optd.git /tmp/optd

### copy files
#cd /tmp/optd
#git commit -a -m "$LOG"
#git push
