#!/bin/sh

# Execute a SQL script
function execSQL() {
	echo "Executing the ${SQL_SCRIPT} SQL script."
	${MYSQL_ROOT} < ${SQL_SCRIPT}
}

####
## SQL Scripts
##
# For creating tables
#SQL_CREATE_TABLE_LOGS="create_table_logs.sql"
#SQL_CREATE_TABLE_CODES="create_table_codes.sql"
SQL_CREATE_TABLE_TMP_MISSING_TZ="create_table_tmp_missing_timezones.sql"
SQL_CREATE_TABLE_DIC_CITIES="create_table_dic_cities.sql"
SQL_CREATE_TABLE_DIC_CODES="create_table_dic_codes.sql"
SQL_CREATE_TABLE_DIC_COUNTRIES="create_table_dic_countries.sql"
SQL_CREATE_TABLE_USER_DETAILS="create_table_user_details.sql"
SQL_CREATE_TABLE_USER_ADDRESS="create_table_user_address.sql"
SQL_CREATE_TABLE_USER_FREQUENT_FLYER="create_table_user_frequent_flyer.sql"
#SQL_CREATE_TABLE_USER_PAYMENT="create_table_user_payment.sql"
SQL_CREATE_TABLE_BOOKINGS="create_table_bookings.sql"
SQL_CREATE_TABLE_BOOKINGS_SEGMENTS="create_table_bookings_segments.sql"
SQL_CREATE_TABLE_BOOKINGS_PASSENGERS="create_table_bookings_passengers.sql"
SQL_CREATE_TABLE_STAT_SEARCHES="create_table_stat_searches.sql"
SQL_CREATE_TABLE_STAT_ERROR="create_table_stat_error.sql"
SQL_CREATE_TABLE_STAT_TRAVEL_SOLUTIONS="create_table_stat_travel_solutions.sql"
SQL_CREATE_TABLE_STAT_TRAVEL_SOLUTIONS_SEGMENTS="create_table_stat_travel_solutions_segments.sql"
SQL_CREATE_TABLE_WS_ERROR="create_table_ws_error.sql"
# For creating views
SQL_CREATE_VIEW_HITS_USERS_ALL_TIMES="create_view_hits_users_all_times.sql"
SQL_CREATE_VIEW_HITS_USERS_DATES="create_view_hits_users_dates.sql"
SQL_CREATE_VIEW_HITS_USERS_ONDS="create_view_hits_users_onds.sql"
SQL_CREATE_VIEW_HITS_USERS_ONDS2="create_view_hits_users_onds2.sql"
SQL_CREATE_VIEW_HITS_USERS_YESTERDAY="create_view_hits_users_yesterday.sql"
SQL_CREATE_VIEW_LATEST_BOOKINGS="create_view_latest_bookings.sql"
SQL_CREATE_VIEW_LATEST_SEARCHES="create_view_latest_searches.sql"
SQL_CREATE_VIEW_BOOKED_TRAVEL_SOLUTIONS="create_view_booked_travel_solutions.sql"
SQL_CREATE_VIEW_NON_BOOKED_TRAVEL_SOLUTIONS="create_view_non_booked_travel_solutions.sql"
# For filling tables
#SQL_FILL_TABLE_LOGS="fill_table_logs.sql"
#SQL_FILL_TABLE_CODES="fill_table_codes.sql"
SQL_FILL_TABLE_TMP_MISSING_TZ="fill_table_tmp_missing_timezones.sql"
SQL_FILL_TABLE_DIC_CITIES="fill_table_dic_cities.sql"
SQL_FILL_TABLE_DIC_CODES="fill_table_dic_codes.sql"
SQL_FILL_TABLE_DIC_COUNTRIES="fill_table_dic_countries.sql"
SQL_FILL_TABLE_USER_DETAILS="fill_table_user_details.sql"
SQL_FILL_TABLE_USER_ADDRESS="fill_table_user_address.sql"
SQL_FILL_TABLE_USER_FREQUENT_FLYER="fill_table_user_frequent_flyer.sql"
#SQL_FILL_TABLE_USER_PAYMENT="fill_table_user_payment.sql"
SQL_FILL_TABLE_BOOKINGS="fill_table_bookings.sql"
SQL_FILL_TABLE_BOOKINGS_SEGMENTS="fill_table_bookings_segments.sql"
SQL_FILL_TABLE_BOOKINGS_PASSENGERS="fill_table_bookings_passengers.sql"
SQL_FILL_TABLE_STAT_SEARCHES="fill_table_stat_searches.sql"
SQL_FILL_TABLE_STAT_ERROR="fill_table_stat_error.sql"
SQL_FILL_TABLE_STAT_TRAVEL_SOLUTIONS="fill_table_stat_travel_solutions.sql"
SQL_FILL_TABLE_STAT_TRAVEL_SOLUTIONS_SEGMENTS="fill_table_stat_travel_solutions_segments.sql"
SQL_FILL_TABLE_WS_ERROR="fill_table_ws_error.sql"

####
## Settings
##
MYSQL_CLIENT="mysql"
MYSQL_USER="geo"
MYSQL_PASSWD="geo"
MYSQL_DB="geo_geonames"
MYSQL_ROOT="${MYSQL_CLIENT} --user=${MYSQL_USER} --password=${MYSQL_PASSWD} --default-character-set=utf8 -D ${MYSQL_DB}"


####
## Create the tables (if they already exist, the tables are dropped)
##
#SQL_SCRIPT=${SQL_CREATE_TABLE_LOGS}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_TABLE_CODES}
#execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_TMP_MISSING_TZ}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_TMP_MISSING_TZ}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_DIC_CITIES}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_DIC_CODES}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_DIC_COUNTRIES}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_USER_DETAILS}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_USER_ADDRESS}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_USER_FREQUENT_FLYER}
execSQL
#SQL_SCRIPT=${SQL_CREATE_TABLE_USER_PAYMENT}
#execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_BOOKINGS}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_BOOKINGS_SEGMENTS}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_BOOKINGS_PASSENGERS}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_STAT_SEARCHES}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_STAT_ERROR}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_STAT_TRAVEL_SOLUTIONS}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_STAT_TRAVEL_SOLUTIONS_SEGMENTS}
execSQL
SQL_SCRIPT=${SQL_CREATE_TABLE_WS_ERROR}
execSQL

####
## Create the views (if they already exist, the views are dropped)
##
#SQL_SCRIPT=${SQL_CREATE_VIEW_HITS_USERS_ALL_TIMES}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_HITS_USERS_DATES}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_HITS_USERS_ONDS}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_HITS_USERS_ONDS2}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_HITS_USERS_YESTERDAY}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_LATEST_BOOKINGS}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_LATEST_SEARCHES}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_BOOKED_TRAVEL_SOLUTIONS}
#execSQL
#SQL_SCRIPT=${SQL_CREATE_VIEW_NON_BOOKED_TRAVEL_SOLUTIONS}
#execSQL

####
## Fill the tables
##
# Fill the codes table
#SQL_SCRIPT=${SQL_FILL_TABLE_LOGS}
#execSQL
#SQL_SCRIPT=${SQL_FILL_TABLE_CODES}
#execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_TMP_MISSING_TZ}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_DIC_CITIES}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_DIC_CODES}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_DIC_COUNTRIES}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_USER_DETAILS}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_USER_ADDRESS}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_USER_FREQUENT_FLYER}
execSQL
#SQL_SCRIPT=${SQL_FILL_TABLE_USER_PAYMENT}
#execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_BOOKINGS}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_BOOKINGS_SEGMENTS}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_BOOKINGS_PASSENGERS}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_STAT_SEARCHES}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_STAT_ERROR}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_STAT_TRAVEL_SOLUTIONS}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_STAT_TRAVEL_SOLUTIONS_SEGMENTS}
execSQL
SQL_SCRIPT=${SQL_FILL_TABLE_WS_ERROR}
execSQL
