#!/bin/sh
#
# Location of this script:
# https://github.com/opentraveldata/opentraveldata/blob/master/ci-scripts/deploy.sh
#
# This script uploads a few OpenTravelData (OPTD) CSV data files
# onto transport-search.org web servers (aliased titsc and titscnew).
# There are two sets of CSV data files:
# 1. CSV data files maintained on this OPTD Git repository itself
#    (https://github.com/opentraveldata/opentraveldata)
#    The ci-scripts/titsc_delivery_map.csv CSV contains the list of CSV files
#    to be copied from the OPTD Git repo to titsc/titscnew
# 2. CSV data files generated by the Quality Assurance (QA) checkers
#    (https://github.com/opentraveldata/quality-assurance/tree/master/checkers)
#    All the CSV files resulting from the QA checkers are to be copied
#    onto titsc/titscnew
#
# The environment variables set by Travis are specified
# in https://travis-ci.com/opentraveldata/opentraveldata/settings.
# It includes the encryption keys (encrypted_dd7324fa5dde_{iv,key})
#

#
export OPTD_QA_DIR="/tmp/opentraveldata-qa"

#
echo "DATA_DIR_BASE=${DATA_DIR_BASE}"

if [ "${DATA_DIR_BASE}" == "" ]
then
        export DATA_DIR_BASE="/var/www/data/optd/qa"
fi

# To be altered with the new target directories
export TODAY_DATE="$(date +%Y-%m-%d)"
export DATA_DIR="${DATA_DIR_BASE}/${TODAY_DATE}"

#
echo "Injecting a few host keys into ~/.ssh/known_hosts"
cat >> ~/.ssh/known_hosts << _EOF
www2-int2.transport-search.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDmslzunyRnmtrJSwaP1vGuS+vTFBoodZRY1Ri+VIXR8qBKa4MGNgX5WfwQIEOCsbme4gzJ4BZHFNY8WAwNl500=
www-int2.transport-search.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKuH70tG6Ep2ibfqkZMnhPhXan9uIEXuQXUMdNG7N8ZSTv713tO1moU/nVl/drrN68Z4bLD+Nj49OIhj/9OM/W8=
_EOF
chmod 600 ~/.ssh/known_hosts

#
#echo "Content of ~/.ssh/config"
#cat ~/.ssh/config
#echo "--"

#
syncToTITsc() {
        #
        echo
	echo "==== Uploading to ${TITSC_SVR} ===="
        echo "Synchronization of the CSV data files onto ${TITSC_SVR}"
        echo

        #
        echo "Creating ${DATA_DIR} on to qa@${TITSC_SVR}..."
        ssh -o StrictHostKeyChecking=no qa@${TITSC_SVR} "mkdir -p ${DATA_DIR}"
        echo "... done"

        #
        echo "Synchronizing ${OPTD_QA_DIR}/results onto qa@${TITSC_SVR}..."
        time rsync -rav --del -e "ssh -o StrictHostKeyChecking=no" ${OPTD_QA_DIR}/results qa@${TITSC_SVR}:${DATA_DIR}/
        echo "... done"

        #
        echo "Synchronizing ${OPTD_QA_DIR}/to_be_checked onto qa@${TITSC_SVR}..."
        time rsync -rav --del -e "ssh -o StrictHostKeyChecking=no" ${OPTD_QA_DIR}/to_be_checked qa@${TITSC_SVR}:${DATA_DIR}/
        echo "... done"

        #
        echo "Compressing all the CSV files in to_be_checked/ on qa@${TITSC_SVR}..."
        time ssh -o StrictHostKeyChecking=no qa@${TITSC_SVR} "bzip2 ${DATA_DIR}/to_be_checked/*.csv"
        echo "... done"

        #
        echo
        echo "==== Done uploading to ${TITSC_SVR} ===="
        echo
}

# Clone the Quality Assurance (QA) repository
echo
echo "Cloning https://github.com/opentraveldata/quality-assurance into ${OPTD_QA_DIR}..."
git clone https://github.com/opentraveldata/quality-assurance.git ${OPTD_QA_DIR}
echo "... done"
echo "==== Run the QA checkers ===="
pushd ${OPTD_QA_DIR}
pip install -r requirements.txt
make PY_EXEC=python checkers
popd
echo "==== QA checkers done ===="

# Copy the files
echo "==== Uploading the files onto titsc/titscnew ===="
n=0
cat ci-scripts/titsc_delivery_map.csv | while read line ; do
  n=$((n+1))
  org_dir="$(echo $line | cut -d^ -f1)"
  csv_filename="$(echo $line | cut -d^ -f2)"
  tgt_dir="$(echo $line | cut -d^ -f3)"
  csv_file="${org_dir}/${csv_filename}"
  if [ ! -f "${csv_file}" ]
  then
    echo "\n#####"
    echo "In ci-scripts/titsc_delivery_map.csv:$n"
    echo "\$org_dir=${org_dir}"
    echo "\$csv_filename=${csv_filename}"
    echo "\$tgt_dir=${tgt_dir}"
    echo "The origin CSV data file '${csv_file}' is missing in this repo"
    echo "It is expected to upload it to titsc/titiscnew into '${DATA_DIR_BASE}${tgt_dir}'"
    echo "If that file has been removed from the OPTD repository, please update ci-scripts/titsc_delivery_map.csv"
    echo "#####\n"
    exit 1
  fi
done

# https://transport-search.org/data/optd/qa
TITSC_SVR="titsc"
syncToTITsc

# https://www2.transport-search.org/data/optd/qa
TITSC_SVR="titscnew"
syncToTITsc

echo "==== Uploading done ===="


